# Generated by Django 3.0.4 on 2020-03-09 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='pack',
            field=models.CharField(max_length=75),
        ),
    ]
